typography_spectrum: 1
color:
  brandColors:
    - '#f3f3f3'
    - '#050505'
    - '#838383'
    - '#333333'
    - '#535353'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50395
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Alli Jiang
  email: allijiangphoto@gmail.com
name: ALLI JIANG
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ALLI JIANG
purpose: []
